#!/bin/bash

# Run terraform fmt on all .tf files in the infrastructure directory - giving error code if made changes, without making changes
# Not bothering here to check which files changed as there aren't many Terraform files yet, so it's pretty quick
terraform fmt -check -list=false infrastructure/*.tf
terraform_fmt_exit=$?
if [ $terraform_fmt_exit -ne 0 ]; then
  echo "Doing Terraform linting."
  # Actually make the changes now, and list changed files
  terraform fmt infrastructure/*.tf
else
  echo "No Terraform files changed."
fi

# List all Java files that have been changed in the current commit
changed_java_files=$(git diff --cached --name-only -- '*.java')

# Run google-java-format on the changed Java files
if [ -n "$changed_java_files" ]; then
  echo "Doing Java linting."
  for file in $changed_java_files; do
    echo "$file"  # List the file
    google-java-format -i "$file"
  done
  google_java_format_exit=1
else
  echo "No Java files changed."
  google_java_format_exit=0
fi

# Exit with an error code if either of the commands failed
if [ $terraform_fmt_exit -ne 0 ] || [ $google_java_format_exit -ne 0 ]; then
  exit 1
fi

# Continue with the commit if both commands succeeded
exit 0
