# For CodeDeploy - specifies how to handle deployment event hooks, and where to get and put files.
version: 0.0
os: linux
# Source files are copied to destination files during the Install Event
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
files:
  - source: target/tournamaths-1.0.jar  # This path is relative to root directory of tournamaths-deployment.zip obtained from S3
    destination: /home/ec2-user/  # This path is absolute directory in the EC2 instance to put the source file
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/rename_jar.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
