version: 0.0
os: linux
# Source files are copied to destination files during the Install Event
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
files:
  - source: /tmp/tournamaths/target/tournamaths.jar
    destination: /home/ec2-user/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  DownloadBundle:
    - location: scripts/download_bundle.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/rename_jar.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
