version: "3.8"
services:
  tournamaths-app:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles:
      - dev
  db:
    image: "postgres:16.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_DB=dev
      # For local database, be very nasty with security, as can only be reached locally.
      - POSTGRES_PASSWORD=password
    profiles:
      - dev
