version: "3.8"
services:
  tournamaths-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/dev
      - spring.datasource.username=admin_user
      # For local database, be very nasty with security, as can only be reached locally.
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.show-sql=true
      - logging.level.org.springframework=DEBUG
      - spring.jpa.properties.hibernate.format_sql=true
      - logging.level.org.hibernate.type=TRACE
      - logging.level.org.springframework.boot.autoconfigure=DEBUG
      - debug=true
    profiles:
      - dev
  db:
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_DB=dev
      # For local database, be very nasty with security, as can only be reached locally.
      - POSTGRES_PASSWORD=password
    profiles:
      - dev
