package com.tournamaths.filter;

import com.tournamaths.util.NonceBean;
import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import org.springframework.beans.factory.annotation.Autowired;

public class CSPFilter implements Filter {
  /*
   * Filter which creates CSP, including with nonce..
   *
   * Doing it this way instead of directly in SecurityConfig since the filter lifecycle matches the request-scoped bean,
   * but the SecurityConfig lifecycle doesn't match the request-scoped bean.
   */

  @Autowired private NonceBean nonceBean;

  @Override
  public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
      throws IOException, ServletException {

    HttpServletResponse httpResp = (HttpServletResponse) response;
    String nonce = nonceBean.getNonce();

    // Allow only a restricted list of scripts and styles.
    // upgrade-insecure-requests requires all resources to be loaded over
    // HTTPS.
    // As the CSP lists both URLs and hashes, it requires resources to match
    // both 1 URL and 1 hash.
    // For readability, I've listed each hash after its script URL.
    String cspPolicy =
        "script-src 'self'"
            + " https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            + " 'sha384-1H217gwSVyLSIfaLxHbE7dRb3v4mYCKbpQvzx0cegeju1MVsGrX5xXxAvs/HgeFs'"
            + " https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js"
            + " 'sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8';"
            + " style-src 'self'"
            + " https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css"
            + " 'sha384-bnKrovjvRzFUSqtvDhPloRir5qWWcx0KhrlfLaR4RXO9IUC+zJBuvclXv/fSdVyk'"
            + " https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css"
            + " 'sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV'"
            // Nonce so dynamic content generated by KaTeX can be trusted
            + " 'nonce-"
            + nonce
            + "';"
            + " upgrade-insecure-requests";
    httpResp.setHeader("Content-Security-Policy", cspPolicy);

    chain.doFilter(request, response);
  }
}
