name: Check Terraform

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Use latest terraform version
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -diff -check
      working-directory: infrastructure
