name: Check Java

on:
  push:

jobs:
  lint:
    name: Lint Java
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # This is Google's Java code formatter. Using it for checking since I can then run it locally and will be consistent.
    # The formatter performs linting, sorts imports, removes unused imports, and other improvements, when run locally.
    # In this Github Action, we print the diff of every incorrectly formatted file, and fail if there is any.
    - name: Get diffs
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--replace"
        skip-commit: true
    - name: Print diffs
      run: git --no-pager diff --exit-code
