name: Lint JavaScript

on:
  push:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21 # Latest as of writing this

    - name: Install Node.js dependencies
      run: sudo npm install eslint eslint-plugin-es6 prettier --global

    - name: Run ESLint
      run: eslint src/main/resources/static/js
