name: 'Deploy to prod'

on:
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: 'Deploy to prod'
    runs-on: ubuntu-latest

    steps:
      - name: Only allow deployment from main branch
        run: |
          if [[ "${{ github.ref }}" != "ref/heads/main" ]]; then
            echo "Should only run deployment from main branch, but github.ref=${{ github.ref }}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        # Checking that actor is owner would be better than only allowing my account to run deployments, but this is just a pet project
        if: github.actor == 'mperry-dev'
        run: terraform apply -auto-approve
